### ISSUE TITLE
Cannot read properties of undefined (reading '/workspaces/cloudflare-starter-kit/.pnp.cjs')

### ISSUE THREAD

**Issue by 374632897** [kriasoft/cloudflare-starter-kit#38]
Hi, I intialized this project in code space, but it throws an error like this when I run `yarn start` after I run `yarn install`. 
so what should i do  to solve this problem?

```bash
Type Error: Cannot read properties of undefined (reading '/workspaces/cloudflare-starter-kit/.pnp.cjs')
    at yne (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:134:54207)
    at QXe (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:134:54676)
    at Object.Jp (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:134:54817)
    at /workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:650:4662
    at Object.vf (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:134:53352)
    at Ih.findPackageLocation (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:650:4617)
    at /workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:184:1268
    at Function.from (<anonymous>)
    at LP (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:184:1012)
    at yue (/workspaces/cloudflare-starter-kit/.yarn/releases/yarn-4.0.0-rc.39.cjs:184:1595)
```

**Comment by BTmedyajans** [comment]
btmedya-db
